name: Detect Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      design-system: ${{ steps.filter.outputs.design-system }}
      new-portfolio: ${{ steps.filter.outputs.new-portfolio }}
      fonts: ${{ steps.filter.outputs.fonts }}
      styling: ${{ steps.filter.outputs.styling }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            design-system:
              - 'packages/design-system/**'
              - '.github/workflows/design-system.yml'
            new-portfolio:
              - 'apps/new-portfolio/**'
              - '.github/workflows/new-portfolio.yml'
            fonts:
              - 'packages/fonts/**'
              - '.github/workflows/fonts.yml'
            styling:
              - 'packages/styling/**'
              - '.github/workflows/styling.yml'
              
      # Save PR info for use in dependent workflows
      - name: Save PR Data
        if: always()
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> pr.json
          echo "PR_HEAD_REF=${{ github.event.pull_request.head.ref }}" >> pr.json
          echo "PR_BASE_REF=${{ github.event.pull_request.base.ref }}" >> pr.json
          echo "DESIGN_SYSTEM_CHANGED=${{ steps.filter.outputs.design-system }}" >> pr.json
          echo "NEW_PORTFOLIO_CHANGED=${{ steps.filter.outputs.new-portfolio }}" >> pr.json
          echo "FONTS_CHANGED=${{ steps.filter.outputs.fonts }}" >> pr.json
          echo "STYLING_CHANGED=${{ steps.filter.outputs.styling }}" >> pr.json
          echo "GITHUB_SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> pr.json
          
      - name: Upload PR Data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-data
          path: pr.json
          retention-days: 1
